//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoNovitas.LoginSample.Repositories.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IdentityExDbEntities : DbContext
    {
        public IdentityExDbEntities()
            : base("name=IdentityExDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserRegistrationToken> UserRegistrationTokens { get; set; }
        public virtual DbSet<Book> Books { get; set; }
    
        public virtual ObjectResult<Author_Get_Result> Author_Get(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Author_Get_Result>("Author_Get", idParameter);
        }
    
        public virtual ObjectResult<Authors_Get_Result> Authors_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Authors_Get_Result>("Authors_Get");
        }
    
        public virtual ObjectResult<AuthorAllData_Get_Result> AuthorAllData_Get(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AuthorAllData_Get_Result>("AuthorAllData_Get", idParameter);
        }
    
        public virtual ObjectResult<AuthorData_Get_Result> AuthorData_Get(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AuthorData_Get_Result>("AuthorData_Get", idParameter);
        }
    
        public virtual int Author_Delete(Nullable<int> id, Nullable<int> userLastModified)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var userLastModifiedParameter = userLastModified.HasValue ?
                new ObjectParameter("UserLastModified", userLastModified) :
                new ObjectParameter("UserLastModified", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Author_Delete", idParameter, userLastModifiedParameter);
        }
    
        public virtual int Author_Save(Nullable<int> id, string firstName, string lastName, string note, string description, Nullable<int> userLastModified)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var userLastModifiedParameter = userLastModified.HasValue ?
                new ObjectParameter("UserLastModified", userLastModified) :
                new ObjectParameter("UserLastModified", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Author_Save", idParameter, firstNameParameter, lastNameParameter, noteParameter, descriptionParameter, userLastModifiedParameter);
        }
    
        public virtual int Author_Insert(string firstName, string lastName, string note, string description, Nullable<int> userCreated)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var userCreatedParameter = userCreated.HasValue ?
                new ObjectParameter("UserCreated", userCreated) :
                new ObjectParameter("UserCreated", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Author_Insert", firstNameParameter, lastNameParameter, noteParameter, descriptionParameter, userCreatedParameter);
        }
    
        public virtual int User_Save(Nullable<int> id, string firstName, string lastName, string email)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("User_Save", idParameter, firstNameParameter, lastNameParameter, emailParameter);
        }
    
        public virtual ObjectResult<Users_Get_Result> Users_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Users_Get_Result>("Users_Get");
        }
    
        public virtual int Book_Delete(Nullable<int> id, Nullable<int> userLastModified)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var userLastModifiedParameter = userLastModified.HasValue ?
                new ObjectParameter("UserLastModified", userLastModified) :
                new ObjectParameter("UserLastModified", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Book_Delete", idParameter, userLastModifiedParameter);
        }
    
        public virtual int Book_Insert(string title, Nullable<int> author, string description, Nullable<int> userCreated)
        {
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var authorParameter = author.HasValue ?
                new ObjectParameter("Author", author) :
                new ObjectParameter("Author", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var userCreatedParameter = userCreated.HasValue ?
                new ObjectParameter("UserCreated", userCreated) :
                new ObjectParameter("UserCreated", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Book_Insert", titleParameter, authorParameter, descriptionParameter, userCreatedParameter);
        }
    
        public virtual int Book_Save(Nullable<int> id, string title, Nullable<int> author, string description, Nullable<int> userLastModified)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var authorParameter = author.HasValue ?
                new ObjectParameter("Author", author) :
                new ObjectParameter("Author", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var userLastModifiedParameter = userLastModified.HasValue ?
                new ObjectParameter("UserLastModified", userLastModified) :
                new ObjectParameter("UserLastModified", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Book_Save", idParameter, titleParameter, authorParameter, descriptionParameter, userLastModifiedParameter);
        }
    
        public virtual ObjectResult<BookData_Get_Result> BookData_Get(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BookData_Get_Result>("BookData_Get", idParameter);
        }
    
        public virtual int ReturnRecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReturnRecords");
        }
    
        public virtual ObjectResult<Books_Get_Result> Books_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Books_Get_Result>("Books_Get");
        }
    }
}
