//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoNovitas.LoginSample.Repositories.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Authors = new HashSet<Author>();
            this.Authors1 = new HashSet<Author>();
            this.Books = new HashSet<Book>();
            this.Books1 = new HashSet<Book>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<Author> Authors1 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<Book> Books1 { get; set; }
    }
}
